import type { CONFIG_DATA } from "../types";

export const DEFAULT_CONFIG: CONFIG_DATA = {
    "target": "",
    "last_checksum": "",
    "directories": [
        ".config/alacritty",
        ".config/hypr",
        ".config/i3", 
        ".config/nvim",
        ".config/polybar",
        ".config/tofi",
        ".config/waybar",
        ".config/dunst",
        ".config/compfy",
        ".config/rofi",
        ".config/kitty",
        ".config/tmux",
        ".config/zsh",
        ".config/fish",
        ".config/starship",
        ".config/git",
        ".config/gtk-3.0",
        ".config/gtk-2.0",
        ".config/gtk-4.0",
        ".bashrc",
        ".zshrc",
        ".vimrc",
        ".xinitrc",
        ".xprofile"
    ],
    "ignore": [
        "**/.env",
        "**/.env.local", 
        "**/.env.production",
        "**/.env.development",
        "**/id_rsa",
        "**/id_ed25519", 
        "**/*.pem",
        "**/*.key",
        "**/secrets.json",
        "**/auth.json",
        "**/.authinfo",
        "**/cache/**",
        "**/Cache/**", 
        "**/tmp/**",
        "**/temp/**",
        "**/.cache/**",
        "**/node_modules/**",
        "**/__pycache__/**",
        "**/.pytest_cache/**",
        "**/*.log",
        "**/logs/**",
        "**/*.db",
        "**/*.sqlite",
        "**/*.sqlite3",
        "**/*.o",
        "**/*.so", 
        "**/*.dylib",
        "**/.git/**"
    ]
};